package main

import (
	"github.com/lessbutter/mealkit/config"
	infra "github.com/lessbutter/mealkit/src"
	"github.com/lessbutter/mealkit/src/model"
	"go.mongodb.org/mongo-driver/mongo"
)

func addCategories(conn *mongo.Client) {
	categories := []model.Category{
		{
			Label:            "김치찌개",
			Name:             "Kimchizzigye",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Kimchizzigye.png",
			Order:            0,
			Onmain:           true,
		},
		{
			Label:            "순두부찌개",
			Name:             "Sundubuzzigye",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Sundubuzzigye.png",
			Order:            1,
			Onmain:           true,
		},
		{
			Label:            "된장찌개",
			Name:             "Duonjangzzigye",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Duonjangzzigye.png",
			Order:            2,
			Onmain:           true,
		},
		{
			Label:            "부대찌개",
			Name:             "Budaezzigye",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Budaezzigye.png",
			Order:            3,
			Onmain:           true,
		},
		{
			Label:            "청국장",
			Name:             "Chunggukjang",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Chunggukjang.png",
			Order:            4,
			Onmain:           false,
		},
		{
			Label:            "마라탕",
			Name:             "Maratang",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Maratang.png",
			Order:            5,
			Onmain:           true,
		},
		{
			Label:            "샤브샤브",
			Name:             "Shabshab",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Shabshab.png",
			Order:            6,
			Onmain:           true,
		},
		{
			Label:            "닭갈비",
			Name:             "Dakkalbi",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Dakkalbi.png",
			Order:            7,
			Onmain:           false,
		},
		{
			Label:            "불고기전골",
			Name:             "Bulgogijeongol",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Bulgogijeongol.png",
			Order:            8,
			Onmain:           false,
		},
		{
			Label:            "곱창전골",
			Name:             "Gobchangjeongol",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Gobchangjeongol.png",
			Order:            9,
			Onmain:           false,
		},
		{
			Label:            "밀푀유나베",
			Name:             "Millefeuille",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Millefeuille.png",
			Order:            10,
			Onmain:           true,
		},
		{
			Label:            "해물탕",
			Name:             "Hamultang",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Hamultang.png",
			Order:            11,
			Onmain:           true,
		},
		{
			Label:            "볶음요리",
			Name:             "Bokum",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Bokum.png",
			Order:            12,
			Onmain:           false,
		},
		{
			Label:            "찜요리",
			Name:             "Zzim",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Zzim.png",
			Order:            13,
			Onmain:           false,
		},
		{
			Label:            "돈까스",
			Name:             "Donkkas",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Donkkas.png",
			Order:            14,
			Onmain:           false,
		},
		{
			Label:            "기타 국/탕/전골",
			Name:             "Etcjeongol",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Etcjeongol.png",
			Order:            15,
			Onmain:           false,
		},
		{
			Label:            "덮밥/비빔밥",
			Name:             "Bibbimbap",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Bibbimbap.png",
			Order:            16,
			Onmain:           true,
		},
		{
			Label:            "면",
			Name:             "Myun",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Myun.png",
			Order:            17,
			Onmain:           true,
		},
		{
			Label:            "스테이크",
			Name:             "Steak",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Steak.png",
			Order:            18,
			Onmain:           true,
		},
		{
			Label:            "고기",
			Name:             "Gogi",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Gogi.png",
			Order:            19,
			Onmain:           true,
		},
		{
			Label:            "파스타",
			Name:             "Pasta",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Pasta.png",
			Order:            20,
			Onmain:           true,
		},
		{
			Label:            "감바스",
			Name:             "Gambas",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Gambas.png",
			Order:            21,
			Onmain:           true,
		},
		{
			Label:            "분식",
			Name:             "Bunsik",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Bunsik.png",
			Order:            22,
			Onmain:           true,
		},
		{
			Label:            "짜글이",
			Name:             "Jjagle",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Jjagle.png",
			Order:            23,
			Onmain:           false,
		},
		{
			Label:            "기타 요리",
			Name:             "Etc",
			Categoryimageurl: "https://mealkit.s3.ap-northeast-2.amazonaws.com/categories/Etc.png",
			Order:            24,
			Onmain:           false,
		},
	}

	infra.AddCategories(conn, categories)
}

func addBrands(conn *mongo.Client) {
	brands := []model.Brand{
		{
			Name:                "프레시지",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/fresheasy.png",
			Order:               0,
			Onmain:              true,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "fresheasy",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/500230195/categories/36e7f87fa6e24e19b30fd5b0c2fae4bb/products?categoryId=36e7f87fa6e24e19b30fd5b0c2fae4bb&categorySearchType=DISPCATG",
		},
		{
			Name:                "마이셰프",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/mychef.png",
			Order:               1,
			Onmain:              true,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "recipebox_mychef",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/500239930/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "프레시밀",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/freshmeal.png",
			Order:               2,
			Onmain:              true,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "fresh-meal",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/101066654/categories/488cad1747f34b01b13a1021cf19230c/products?categoryId=488cad1747f34b01b13a1021cf19230c&categorySearchType=DISPCATG",
		},
		{
			Name:                "푸드어셈블",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/foodassemble.png",
			Order:               3,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "foodasb",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/100029405/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "앙트레",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/entree.png",
			Order:               4,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "entree_organico",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/100009290/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "파파쿡",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/papacook.png",
			Order:               5,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "friendsfood",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/500289590/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "애슐리",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/ashley.png",
			Order:               6,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "elandparkfood",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/100002411/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "쿡솜씨",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/cooksomssi.png",
			Order:               7,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "cooksomssi",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/100179980/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "올쿡",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/allcook.png",
			Order:               8,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "allcook_store",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/100885144/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "닥터키친",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/drkitchen.png",
			Order:               9,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "dr_kitchen",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/100147551/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "파우즈",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/pause.png",
			Order:               12,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "pausemealkit",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/101089550/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "맛수러움",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/matsuruum.png",
			Order:               16,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "bangpofishery",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/500149336/categories/a015ed45aa724cb39516a0def00a1bdb/products?categoryId=a015ed45aa724cb39516a0def00a1bdb&categorySearchType=DISPCATG",
		},
		{
			Name:                "자연맛남",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/naturefood.png",
			Order:               13,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "ifoodmall",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/500057665/categories/92ed12de0bbd41b99eb9a7bd15a06ab7/products?categoryId=92ed12de0bbd41b99eb9a7bd15a06ab7&categorySearchType=DISPCATG",
		},
		{
			Name:                "아로이키친",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/rama.png",
			Order:               18,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "rama",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/100875480/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "쿡킷",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/momil.png",
			Order:               18,
			Onmain:              false,
			CrawlFrom:           "cookit",
			SmartstoreBrandName: "",
			CrawlingUrl:         "https://www.cjcookit.com/pc/menu/menuProdList.json",
		},
		{
			Name:                "피코크",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/peacock.png",
			Order:               15,
			Onmain:              false,
			CrawlFrom:           "emart",
			SmartstoreBrandName: "",
			CrawlingUrl:         "http://emart.ssg.com/specialStore/ssgpeacock/ajaxSubItemList.ssg?isCornrItemShow=false&pageSize=80&ctgId=6000073847",
		},
		{
			Name:                "모노키친",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/monokitchen.png",
			Order:               14,
			Onmain:              false,
			CrawlFrom:           "monokitchen",
			SmartstoreBrandName: "",
			CrawlingUrl:         "",
		},
		{
			Name:                "심플리쿡",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/simplycook.png",
			Order:               17,
			Onmain:              false,
			CrawlFrom:           "gsshop",
			SmartstoreBrandName: "",
			CrawlingUrl:         "https://api.gsecretail.com/dp/fr/ssevntmgnt/ssevent-detail?ssevntId=3111&mallId=20&dspScrSpCd=01&storId=3006",
		},
		{
			Name:                "테이스티나인",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/tasty9.png",
			Order:               19,
			Onmain:              false,
			CrawlFrom:           "tasty9",
			SmartstoreBrandName: "",
			CrawlingUrl:         "",
		},
	}

	infra.AddBrands(conn, brands)
}

func main() {
	conf := config.GetConfiguration()
	conn := infra.MongoConn(conf)
	addCategories(conn)
	addBrands(conn)
}
