package seeds

import (
	"log"
	"strconv"

	infra "github.com/lessbutter/momeal-api/src"
	"github.com/lessbutter/momeal-api/src/model"
)

func AddBrands() {
	brands := []model.Brand{
		{
			Name:                "프레시지",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/fresheasy.png",
			Order:               0,
			Onmain:              true,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "fresheasy",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/500230195/categories/36e7f87fa6e24e19b30fd5b0c2fae4bb/products?categoryId=36e7f87fa6e24e19b30fd5b0c2fae4bb&categorySearchType=DISPCATG",
		},
		{
			Name:                "마이셰프",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/mychef.png",
			Order:               1,
			Onmain:              true,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "recipebox_mychef",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/500239930/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "프레시밀",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/freshmeal.png",
			Order:               2,
			Onmain:              true,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "fresh-meal",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/101066654/categories/488cad1747f34b01b13a1021cf19230c/products?categoryId=488cad1747f34b01b13a1021cf19230c&categorySearchType=DISPCATG",
		},
		{
			Name:                "푸드어셈블",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/foodassemble.png",
			Order:               3,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "foodasb",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/100029405/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "앙트레",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/entree.png",
			Order:               4,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "entree_organico",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/100009290/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "파파쿡",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/papacook.png",
			Order:               5,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "friendsfood",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/500289590/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "애슐리",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/ashley.png",
			Order:               6,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "elandparkfood",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/100002411/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "쿡솜씨",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/cooksomssi.png",
			Order:               7,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "cooksomssi",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/100179980/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "올쿡",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/allcook.png",
			Order:               8,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "allcook_store",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/100885144/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "닥터키친",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/drkitchen.png",
			Order:               9,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "dr_kitchen",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/100147551/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "파우즈",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/pause.png",
			Order:               12,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "pausemealkit",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/101089550/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "맛수러움",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/matsuruum.png",
			Order:               16,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "bangpofishery",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/500149336/categories/a015ed45aa724cb39516a0def00a1bdb/products?categoryId=a015ed45aa724cb39516a0def00a1bdb&categorySearchType=DISPCATG",
		},
		{
			Name:                "자연맛남",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/naturefood.png",
			Order:               13,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "ifoodmall",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/500057665/categories/92ed12de0bbd41b99eb9a7bd15a06ab7/products?categoryId=92ed12de0bbd41b99eb9a7bd15a06ab7&categorySearchType=DISPCATG",
		},
		{
			Name:                "아로이키친",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/rama.png",
			Order:               18,
			Onmain:              false,
			CrawlFrom:           "smartstore",
			SmartstoreBrandName: "rama",
			CrawlingUrl:         "https://smartstore.naver.com/i/v1/stores/100875480/categories/ALL/products?categoryId=ALL&categorySearchType=DISPCATG",
		},
		{
			Name:                "쿡킷",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/momil.png",
			Order:               18,
			Onmain:              false,
			CrawlFrom:           "cookit",
			SmartstoreBrandName: "",
			CrawlingUrl:         "https://www.cjcookit.com/pc/menu/menuProdList.json",
		},
		{
			Name:                "피코크",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/peacock.png",
			Order:               15,
			Onmain:              false,
			CrawlFrom:           "emart",
			SmartstoreBrandName: "",
			CrawlingUrl:         "http://emart.ssg.com/specialStore/ssgpeacock/ajaxSubItemList.ssg?isCornrItemShow=false&pageSize=80&ctgId=6000073847",
		},
		{
			Name:                "모노키친",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/monokitchen.png",
			Order:               14,
			Onmain:              false,
			CrawlFrom:           "monokitchen",
			SmartstoreBrandName: "",
			CrawlingUrl:         "",
		},
		{
			Name:                "심플리쿡",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/simplycook.png",
			Order:               17,
			Onmain:              false,
			CrawlFrom:           "gsshop",
			SmartstoreBrandName: "",
			CrawlingUrl:         "https://api.gsecretail.com/dp/fr/ssevntmgnt/ssevent-detail?ssevntId=3111&mallId=20&dspScrSpCd=01&storId=3006",
		},
		{
			Name:                "테이스티나인",
			Brandimageurl:       "https://mealkit.s3.ap-northeast-2.amazonaws.com/brands/tasty9.png",
			Order:               19,
			Onmain:              false,
			CrawlFrom:           "tasty9",
			SmartstoreBrandName: "",
			CrawlingUrl:         "",
		},
	}

	infra.AddBrands(brands)
	log.Println(strconv.Itoa(len(brands)) + " Brands Addition Finished")
}
